### ISSUE TITLE
Crash: https://www.ekioh.com/flow-browser/

### ISSUE THREAD

**Issue by CanadaHonk** [CanadaHonk/shadow#11]
RangeError: Maximum call stack size exceeded
    at String.replace (<anonymous>)
    at LayoutNode.resolveValue (http://localhost:1337/engine/layout.js:369:14)
    at LayoutNode.lengthAbs (http://localhost:1337/engine/layout.js:502:20)
    at LayoutNode.contentHeight (http://localhost:1337/engine/layout.js:792:19)
    at LayoutNode.<anonymous> (http://localhost:1337/engine/layout.js:89:27)
    at LayoutNode.height (http://localhost:1337/engine/layout.js:895:17)
    at LayoutNode.<anonymous> (http://localhost:1337/engine/layout.js:89:27)
    at LayoutNode.endY (http://localhost:1337/engine/layout.js:946:35)
    at LayoutNode.<anonymous> (http://localhost:1337/engine/layout.js:89:27)
    at LayoutNode.contentHeight (http://localhost:1337/engine/layout.js:813:21)

**Comment by CanadaHonk** [comment]
Probably duplicate of #8 but I'll leave open for now
