### ISSUE TITLE
Crash report: https://lukewarlow.dev

### ISSUE THREAD

**Issue by lukewarlow** [CanadaHonk/shadow#7]
TypeError: x is not iterable
    at LayoutNode.lengthAbs (https://shadow.goose.icu/engine/layout.js:524:21)
    at LayoutNode.lineHeight (https://shadow.goose.icu/engine/layout.js:642:17)
    at LayoutNode.<anonymous> (https://shadow.goose.icu/engine/layout.js:89:27)
    at LayoutNode.resolveValue (https://shadow.goose.icu/engine/layout.js:366:42)
    at LayoutNode.lengthAbs (https://shadow.goose.icu/engine/layout.js:502:20)
    at LayoutNode.lineHeight (https://shadow.goose.icu/engine/layout.js:642:17)
    at LayoutNode.<anonymous> (https://shadow.goose.icu/engine/layout.js:89:27)
    at LayoutNode.resolveValue (https://shadow.goose.icu/engine/layout.js:366:42)
    at LayoutNode.lengthAbs (https://shadow.goose.icu/engine/layout.js:502:20)
    at LayoutNode.lineHeight (https://shadow.goose.icu/engine/layout.js:642:17)

**Comment by CanadaHonk** [comment]
(Still crashes but fixes this error so closed)
